// Data seed baku untuk direktori rumah sakit, dimuat oleh `pnpm db:seed`.
// Rumah sakit Indonesia nyata — nama, kota, provinsi, kepemilikan (type),
// kelas Permenkes, dan kategori akurat; alamat, nomor telepon, jumlah tempat
// tidur, tahun berdiri, dan nama dokter adalah placeholder representatif
// untuk direktori demo, bukan catatan resmi.
//
// `image_url` diisi foto asli rumah sakit jika tersedia: 15 hotlink dari
// Wikimedia (upload.wikimedia.org, CC / domain publik) dan 8 dari foto
// publik rumah sakit sendiri di rs.kemkes.go.id (kemenkesrs S3). 19 sisanya
// tidak punya foto bebas pakai, jadi `image_url` diisi "" dan aplikasi
// memakai placeholder bawaannya — bukan foto stok sebagai pengganti gedung
// asli.
//
// `supabase/seed.sql` adalah cermin parsial usang dan tidak dipakai perintah manapun.
export const HOSPITALS = [
  {
    slug: "rs-premier-bintaro",
    name: "RS Premier Bintaro",
    short_name: "Premier Bintaro",
    location: "Tangerang Selatan",
    province: "Banten",
    address: "Jl. Bintaro Utama Sektor 3A, Tangerang Selatan, Banten 15224",
    phone: "(021) 7456-8888",
    type: "Rumah Sakit Swasta",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RS Premier Bintaro adalah rumah sakit swasta terkemuka dengan layanan kesehatan komprehensif dan teknologi medis terkini. Kami berkomitmen memberikan perawatan terbaik dengan standar internasional JCI.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 315,
    established: 1996,
    services: [
      "Ortopedi",
      "Kardiologi",
      "IGD 24 Jam",
      "Radiologi",
      "Laboratorium",
      "Bedah Umum",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "NICU",
      "Kamar Operasi",
      "CT Scan",
      "MRI",
      "Hemodialisis",
      "Apotek 24 Jam",
    ],
    specialists: [
      {
        name: "Dr. Ahmad Firmansyah, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 09:00–14:00",
        image_id: "1612349317-34f14cbbdef8",
      },
      {
        name: "Dr. Siti Rahayu, Sp.OT",
        specialty: "Ortopedi",
        schedule: "Selasa – Sabtu, 10:00–15:00",
        image_id: "1594824476967-bef8d2f54537",
      },
      {
        name: "Dr. Budi Wibowo, Sp.An",
        specialty: "Anestesi",
        schedule: "Setiap hari (on-call)",
        image_id: "1582750433449-648ed127bb54",
      },
    ],
    operational_hours: [
      { day: "Senin – Jumat", hours: "Buka 24 Jam" },
      { day: "Sabtu – Minggu", hours: "Buka 24 Jam" },
      { day: "IGD", hours: "Buka 24 Jam" },
    ],
    is_active: true,
  },
  {
    slug: "siloam-kebon-jeruk",
    name: "Siloam Hospitals Kebon Jeruk",
    short_name: "Siloam Kebon Jeruk",
    location: "Jakarta Barat",
    province: "DKI Jakarta",
    address: "Jl. Perjuangan No. 8, Kebon Jeruk, Jakarta Barat 11530",
    phone: "(021) 5666-5555",
    type: "Rumah Sakit Swasta",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "Siloam Hospitals Kebon Jeruk menyediakan layanan kesehatan yang komprehensif dengan dokter-dokter berpengalaman dan fasilitas modern untuk memastikan kesehatan optimal bagi seluruh keluarga Anda.",
    image_url: "",
    is_open_24h: false,
    closing_time: "22:00",
    beds: 220,
    established: 2004,
    services: ["Mata", "THT", "Ibu & Anak", "Penyakit Dalam", "Bedah"],
    facilities: [
      "Kamar Operasi",
      "Laboratorium",
      "Radiologi",
      "Apotek",
      "Fisioterapi",
      "USG",
    ],
    specialists: [
      {
        name: "Dr. Budi Santoso, Sp.M",
        specialty: "Mata",
        schedule: "Senin – Jumat, 08:00–16:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Dewi Lestari, Sp.THT",
        specialty: "THT",
        schedule: "Senin, Rabu, Jumat, 09:00–13:00",
        image_id: "1559839734-2b71ea197ec2",
      },
      {
        name: "Dr. Anisa Putri, Sp.OG",
        specialty: "Kebidanan & Kandungan",
        schedule: "Selasa – Sabtu, 08:00–15:00",
        image_id: "1594824476967-bef8d2f54537",
      },
    ],
    operational_hours: [
      { day: "Senin – Jumat", hours: "07:00 – 22:00" },
      { day: "Sabtu", hours: "07:00 – 20:00" },
      { day: "Minggu", hours: "08:00 – 18:00" },
    ],
    is_active: true,
  },
  {
    slug: "rs-pondok-indah",
    name: "RS Pondok Indah – Pondok Indah",
    short_name: "RS Pondok Indah",
    location: "Jakarta Selatan",
    province: "DKI Jakarta",
    address: "Jl. Metro Duta Kav. UE, Pondok Indah, Jakarta Selatan 12310",
    phone: "(021) 7695-1111",
    type: "Rumah Sakit Swasta",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RS Pondok Indah adalah salah satu rumah sakit terbaik di Indonesia dengan pengakuan internasional JCI. Kami menghadirkan layanan medis tingkat tinggi dengan teknologi terdepan dan tim dokter spesialis terkemuka.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/2e/RS_Pondok_Indah_-_Pondok_Indah.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 406,
    established: 1986,
    services: ["Onkologi", "Kardiologi", "Neurologi", "Ortopedi", "IGD 24 Jam"],
    facilities: [
      "ICU",
      "PICU",
      "NICU",
      "PET Scan",
      "MRI 3T",
      "Gamma Knife",
      "Apotek 24 Jam",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Hendra Gunawan, Sp.OnK",
        specialty: "Onkologi",
        schedule: "Senin – Jumat, 10:00–15:00",
        image_id: "1612349317-34f14cbbdef8",
      },
      {
        name: "Dr. Maya Indrawati, Sp.S",
        specialty: "Neurologi",
        schedule: "Selasa, Kamis, 09:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
    ],
    operational_hours: [
      { day: "Senin – Minggu", hours: "Buka 24 Jam" },
      { day: "IGD", hours: "Buka 24 Jam" },
    ],
    is_active: true,
  },
  {
    slug: "rscm-jakarta",
    name: "RSUP Dr. Cipto Mangunkusumo",
    short_name: "RSCM",
    location: "Jakarta Pusat",
    province: "DKI Jakarta",
    address: "Jl. Diponegoro No. 71, Kenari, Senen, Jakarta Pusat 10430",
    phone: "(021) 500-135",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSCM adalah rumah sakit umum pusat nasional dan pusat rujukan tertinggi yang menjadi kebanggaan bangsa Indonesia, dengan layanan kesehatan komprehensif untuk semua kalangan masyarakat.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/8/85/Ciptomangun-hospital.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 1500,
    established: 1919,
    services: [
      "Semua Spesialis",
      "IGD 24 Jam",
      "Onkologi",
      "Transplantasi",
      "Bedah Saraf",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "PICU",
      "NICU",
      "Kamar Operasi",
      "Hemodialisis",
      "Radioterapi",
      "CT Scan",
    ],
    specialists: [
      {
        name: "Prof. Dr. Andi Muliawan, Sp.BS",
        specialty: "Bedah Saraf",
        schedule: "Senin, Rabu, Jumat, 08:00–12:00",
        image_id: "1582750433449-648ed127bb54",
      },
      {
        name: "Dr. Kartini Wahyono, Sp.PD-KHOM",
        specialty: "Hematologi-Onkologi",
        schedule: "Selasa – Kamis, 09:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
    ],
    operational_hours: [
      { day: "Senin – Minggu", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 16:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rs-medistra",
    name: "RS Medistra",
    short_name: "Medistra",
    location: "Jakarta Selatan",
    province: "DKI Jakarta",
    address: "Jl. Jend. Gatot Subroto Kav. 59, Kuningan, Jakarta Selatan 12950",
    phone: "(021) 5210-3333",
    type: "Rumah Sakit Swasta",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RS Medistra mengutamakan pelayanan kesehatan yang personal dan berkualitas tinggi. Dengan tim dokter spesialis berpengalaman, kami berkomitmen memberikan diagnosis dan pengobatan yang tepat dan terpercaya.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Rumah_Sakit_Medistra_%28Februari_2025%29.jpg",
    is_open_24h: false,
    closing_time: "21:00",
    beds: 179,
    established: 1991,
    services: ["Kardiologi", "Onkologi", "Penyakit Dalam", "Bedah", "Urologi"],
    facilities: [
      "ICU",
      "Cardiac Cath Lab",
      "CT Scan",
      "MRI",
      "Laboratorium",
      "Apotek",
      "Fisioterapi",
    ],
    specialists: [
      {
        name: "Dr. Rizal Armadi, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 09:00–15:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Nurul Aini, Sp.PD-KHOM",
        specialty: "Onkologi",
        schedule: "Senin, Rabu, Jumat, 08:00–13:00",
        image_id: "1594824476967-bef8d2f54537",
      },
    ],
    operational_hours: [
      { day: "Senin – Jumat", hours: "07:00 – 21:00" },
      { day: "Sabtu", hours: "07:00 – 18:00" },
      { day: "Minggu", hours: "08:00 – 15:00" },
    ],
    is_active: true,
  },
  {
    slug: "siloam-tb-simatupang",
    name: "Siloam Hospitals TB Simatupang",
    short_name: "Siloam TB Simatupang",
    location: "Jakarta Selatan",
    province: "DKI Jakarta",
    address:
      "Jl. Letjen TB Simatupang Kav. 10, Cilandak, Jakarta Selatan 12430",
    phone: "(021) 7884-8888",
    type: "Rumah Sakit Swasta",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "Siloam Hospitals TB Simatupang mengkhususkan diri dalam pelayanan ibu dan anak, dengan fasilitas modern dan tim dokter spesialis yang berpengalaman untuk memastikan kesehatan ibu dan buah hati.",
    image_url: "",
    is_open_24h: false,
    closing_time: "22:00",
    beds: 280,
    established: 2013,
    services: ["Ibu & Anak", "Pediatri", "Ginekologi", "Bedah", "Laboratorium"],
    facilities: [
      "NICU",
      "Kamar Bersalin",
      "Laboratorium",
      "USG 4D",
      "Apotek",
      "Fisioterapi",
      "Laktasi",
    ],
    specialists: [
      {
        name: "Dr. Linda Kusuma, Sp.OG",
        specialty: "Ginekologi & Kebidanan",
        schedule: "Senin – Jumat, 09:00–16:00",
        image_id: "1594824476967-bef8d2f54537",
      },
      {
        name: "Dr. Riko Pratama, Sp.A",
        specialty: "Pediatri",
        schedule: "Setiap hari, 08:00–20:00",
        image_id: "1612349317-34f14cbbdef8",
      },
    ],
    operational_hours: [
      { day: "Senin – Jumat", hours: "07:00 – 22:00" },
      { day: "Sabtu – Minggu", hours: "08:00 – 20:00" },
    ],
    is_active: true,
  },

  // ── Jawa Barat ──────────────────────────────────────────────────────────
  {
    slug: "rsup-hasan-sadikin-bandung",
    name: "RSUP Dr. Hasan Sadikin",
    short_name: "RSHS Bandung",
    location: "Bandung",
    province: "Jawa Barat",
    address: "Jl. Pasteur No. 38, Pasteur, Sukajadi, Kota Bandung 40161",
    phone: "(022) 2034953",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP Dr. Hasan Sadikin adalah rumah sakit rujukan utama untuk wilayah Jawa Barat dengan layanan medis lengkap dan pusat pendidikan kedokteran.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/44/RSHS_Bandung_-_panoramio.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 1000,
    established: 1923,
    services: ["IGD 24 Jam", "Onkologi", "Kardiologi", "Bedah Saraf"],
    facilities: ["IGD 24 Jam", "ICU", "Radioterapi", "CT Scan", "Hemodialisis"],
    specialists: [
      {
        name: "Dr. Wawan Setiawan, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 08:00–14:00",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 15:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rs-santo-borromeus-bandung",
    name: "RS Santo Borromeus",
    short_name: "RS Borromeus",
    location: "Bandung",
    province: "Jawa Barat",
    address:
      "Jl. Ir. H. Juanda No. 100, Lebakgede, Coblong, Kota Bandung 40132",
    phone: "(022) 2552000",
    type: "Rumah Sakit Swasta",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RS Santo Borromeus adalah rumah sakit swasta tertua di Bandung dengan layanan kesehatan menyeluruh untuk keluarga.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/RS_Santo_Borromeus_11.jpg",
    is_open_24h: false,
    closing_time: "21:00",
    beds: 400,
    established: 1921,
    services: ["Penyakit Dalam", "Ibu & Anak", "Bedah", "Laboratorium"],
    facilities: ["Kamar Operasi", "ICU", "NICU", "Radiologi", "Apotek"],
    specialists: [
      {
        name: "Dr. Maria Fransiska, Sp.A",
        specialty: "Pediatri",
        schedule: "Senin – Sabtu, 09:00–15:00",
      },
    ],
    operational_hours: [
      { day: "Senin – Sabtu", hours: "07:00 – 21:00" },
      { day: "Minggu", hours: "08:00 – 14:00" },
    ],
    is_active: true,
  },

  // ── Jawa Tengah ─────────────────────────────────────────────────────────
  {
    slug: "rsup-dr-kariadi-semarang",
    name: "RSUP Dr. Kariadi",
    short_name: "RS Kariadi",
    location: "Semarang",
    province: "Jawa Tengah",
    address:
      "Jl. Dr. Sutomo No. 16, Randusari, Semarang Selatan, Kota Semarang 50244",
    phone: "(024) 8413476",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP Dr. Kariadi adalah rumah sakit rujukan tertinggi di Jawa Tengah dengan fasilitas medis lengkap dan pusat pendidikan.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Rs.Karyadi.JPG",
    is_open_24h: true,
    closing_time: null,
    beds: 900,
    established: 1925,
    services: ["IGD 24 Jam", "Jantung Terpadu", "Onkologi", "Nefrologi"],
    facilities: ["IGD 24 Jam", "ICU", "Cath Lab", "MRI", "Hemodialisis"],
    specialists: [
      {
        name: "Dr. Bagus Prakoso, Sp.PD",
        specialty: "Penyakit Dalam",
        schedule: "Senin – Jumat, 08:00–13:00",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rsi-sultan-agung-semarang",
    name: "RS Islam Sultan Agung",
    short_name: "RSI Sultan Agung",
    location: "Semarang",
    province: "Jawa Tengah",
    address:
      "Jl. Raya Kaligawe KM. 4, Terboyo Kulon, Genuk, Kota Semarang 50112",
    phone: "(024) 6580019",
    type: "Rumah Sakit Swasta",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RS Islam Sultan Agung menghadirkan pelayanan kesehatan yang islami dan profesional bagi masyarakat Semarang dan sekitarnya.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 350,
    established: 1971,
    services: ["IGD 24 Jam", "Mata", "Ibu & Anak", "Bedah"],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Kamar Operasi",
      "Laboratorium",
      "Apotek",
    ],
    specialists: [
      {
        name: "Dr. Nur Hidayat, Sp.M",
        specialty: "Mata",
        schedule: "Senin – Jumat, 08:00–14:00",
      },
    ],
    operational_hours: [{ day: "IGD", hours: "Buka 24 Jam" }],
    is_active: true,
  },

  // ── Jawa Timur ──────────────────────────────────────────────────────────
  {
    slug: "rsud-dr-soetomo-surabaya",
    name: "RSUD Dr. Soetomo",
    short_name: "RS Dr. Soetomo",
    location: "Surabaya",
    province: "Jawa Timur",
    address:
      "Jl. Mayjen Prof. Dr. Moestopo No. 6-8, Airlangga, Gubeng, Kota Surabaya 60286",
    phone: "(031) 5501078",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Dr. Soetomo adalah rumah sakit rujukan utama untuk Indonesia Timur dengan layanan subspesialis lengkap.",
    image_url: "https://upload.wikimedia.org/wikipedia/id/a/a9/Rsudrsoetomo1.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 1500,
    established: 1938,
    services: ["IGD 24 Jam", "Onkologi", "Bedah Saraf", "Transplantasi"],
    facilities: ["IGD 24 Jam", "ICU", "PICU", "Radioterapi", "Hemodialisis"],
    specialists: [
      {
        name: "Dr. Slamet Riyadi, Sp.B",
        specialty: "Bedah Umum",
        schedule: "Selasa & Kamis, 09:00–13:00",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:00 – 15:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rs-premier-surabaya",
    name: "RS Premier Surabaya",
    short_name: "Premier Surabaya",
    location: "Surabaya",
    province: "Jawa Timur",
    address:
      "Jl. Nginden Intan Barat No. B, Ngenden Jangkungan, Sukolilo, Kota Surabaya 60118",
    phone: "(031) 5993211",
    type: "Rumah Sakit Swasta",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RS Premier Surabaya menyediakan layanan kesehatan berstandar internasional dengan teknologi medis mutakhir.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 168,
    established: 1998,
    services: ["IGD 24 Jam", "Kardiologi", "Ortopedi", "Radiologi"],
    facilities: ["IGD 24 Jam", "ICU", "Cath Lab", "CT Scan", "MRI"],
    specialists: [
      {
        name: "Dr. Arya Wardhana, Sp.OT",
        specialty: "Ortopedi",
        schedule: "Senin – Jumat, 10:00–15:00",
      },
    ],
    operational_hours: [{ day: "IGD", hours: "Buka 24 Jam" }],
    is_active: true,
  },

  // ── DI Yogyakarta ──────────────────────────────────────────────────────
  {
    slug: "rsup-dr-sardjito-yogyakarta",
    name: "RSUP Dr. Sardjito",
    short_name: "RS Sardjito",
    location: "Sleman",
    province: "DI Yogyakarta",
    address:
      "Jl. Kesehatan No. 1, Sekip, Sinduadi, Mlati, Kabupaten Sleman 55284",
    phone: "(0274) 631190",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP Dr. Sardjito adalah rumah sakit rujukan untuk DI Yogyakarta dan Jawa Tengah bagian selatan, terintegrasi dengan FK UGM.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Sardjito_hospital_in_Yogyakarta_city.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 750,
    established: 1982,
    services: ["IGD 24 Jam", "Onkologi", "Kardiologi", "Neurologi"],
    facilities: ["IGD 24 Jam", "ICU", "PET Scan", "Cath Lab", "Hemodialisis"],
    specialists: [
      {
        name: "Dr. Retno Palupi, Sp.S",
        specialty: "Neurologi",
        schedule: "Senin, Rabu, Jumat, 08:00–13:00",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Bali ───────────────────────────────────────────────────────────────
  {
    slug: "rsup-prof-ngoerah-denpasar",
    name: "RSUP Prof. Dr. I.G.N.G. Ngoerah",
    short_name: "RS Ngoerah",
    location: "Denpasar",
    province: "Bali",
    address:
      "Jl. Diponegoro, Dauh Puri Klod, Denpasar Barat, Kota Denpasar 80113",
    phone: "(0361) 227911",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP Prof. Dr. I.G.N.G. Ngoerah (dahulu RSUP Sanglah) adalah rumah sakit rujukan tertinggi di Bali dan Nusa Tenggara.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/0/0e/SanglahER.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 800,
    established: 1959,
    services: ["IGD 24 Jam", "Jantung", "Onkologi", "Bedah Plastik"],
    facilities: ["IGD 24 Jam", "ICU", "Cath Lab", "CT Scan", "Hemodialisis"],
    specialists: [
      {
        name: "Dr. Gede Wirawan, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 08:00–13:00",
      },
    ],
    operational_hours: [{ day: "IGD", hours: "Buka 24 Jam" }],
    is_active: true,
  },

  // ── Sumatera Utara ─────────────────────────────────────────────────────
  {
    slug: "rsup-h-adam-malik-medan",
    name: "RSUP H. Adam Malik",
    short_name: "RS Adam Malik",
    location: "Medan",
    province: "Sumatera Utara",
    address:
      "Jl. Bunga Lau No. 17, Kemenangan Tani, Medan Tuntungan, Kota Medan 20136",
    phone: "(061) 8360051",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP H. Adam Malik adalah rumah sakit rujukan untuk wilayah Sumatera bagian utara dengan layanan subspesialis lengkap.",
    image_url: "https://kemenkesrs.s3.ap-southeast-3.amazonaws.com/899/75_GedungCMU1.webp",
    is_open_24h: true,
    closing_time: null,
    beds: 700,
    established: 1991,
    services: ["IGD 24 Jam", "Onkologi", "Jantung", "Nefrologi"],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Radioterapi",
      "Cath Lab",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Rudi Hartono, Sp.PD-KGH",
        specialty: "Nefrologi",
        schedule: "Selasa & Kamis, 09:00–13:00",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Sumatera Selatan ───────────────────────────────────────────────────
  {
    slug: "rsup-mohammad-hoesin-palembang",
    name: "RSUP Dr. Mohammad Hoesin",
    short_name: "RS Mohammad Hoesin",
    location: "Palembang",
    province: "Sumatera Selatan",
    address:
      "Jl. Jenderal Sudirman KM. 3,5, Sekip Jaya, Kemuning, Kota Palembang 30126",
    phone: "(0711) 354088",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP Dr. Mohammad Hoesin adalah rumah sakit rujukan utama di Sumatera bagian selatan.",
    image_url: "https://kemenkesrs.s3.ap-southeast-3.amazonaws.com/555/RSMH.webp",
    is_open_24h: true,
    closing_time: null,
    beds: 900,
    established: 1957,
    services: ["IGD 24 Jam", "Jantung Terpadu", "Onkologi", "Bedah Saraf"],
    facilities: ["IGD 24 Jam", "ICU", "Cath Lab", "CT Scan", "Hemodialisis"],
    specialists: [
      {
        name: "Dr. Fitri Handayani, Sp.OG",
        specialty: "Kebidanan & Kandungan",
        schedule: "Senin – Jumat, 08:00–13:00",
      },
    ],
    operational_hours: [{ day: "IGD", hours: "Buka 24 Jam" }],
    is_active: true,
  },

  // ── Sulawesi Selatan ───────────────────────────────────────────────────
  {
    slug: "rsup-wahidin-sudirohusodo-makassar",
    name: "RSUP Dr. Wahidin Sudirohusodo",
    short_name: "RS Wahidin",
    location: "Makassar",
    province: "Sulawesi Selatan",
    address:
      "Jl. Perintis Kemerdekaan KM. 11, Tamalanrea Indah, Kota Makassar 90245",
    phone: "(0411) 584677",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP Dr. Wahidin Sudirohusodo adalah rumah sakit rujukan tertinggi untuk kawasan timur Indonesia.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Gedung_Pusat_Pelayanan_Ibu_%26_Anak%2C_Rumah_Sakit_Wahidin_Sudirohusodo_%282024%29.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 750,
    established: 1957,
    services: ["IGD 24 Jam", "Jantung", "Onkologi", "Transplantasi Ginjal"],
    facilities: ["IGD 24 Jam", "ICU", "Cath Lab", "MRI", "Hemodialisis"],
    specialists: [
      {
        name: "Dr. Andi Baso, Sp.B-KBD",
        specialty: "Bedah Digestif",
        schedule: "Senin & Rabu, 09:00–13:00",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Kalimantan Timur ───────────────────────────────────────────────────
  {
    slug: "rsud-abdul-wahab-sjahranie-samarinda",
    name: "RSUD Abdul Wahab Sjahranie",
    short_name: "RSUD AWS",
    location: "Samarinda",
    province: "Kalimantan Timur",
    address:
      "Jl. Palang Merah Indonesia No. 1, Sidodadi, Samarinda Ulu, Kota Samarinda 75123",
    phone: "(0541) 738118",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Abdul Wahab Sjahranie adalah rumah sakit rujukan utama untuk Provinsi Kalimantan Timur.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 600,
    established: 1933,
    services: ["IGD 24 Jam", "Jantung", "Onkologi", "Trauma Center"],
    facilities: ["IGD 24 Jam", "ICU", "Cath Lab", "CT Scan", "Hemodialisis"],
    specialists: [
      {
        name: "Dr. Yusuf Ramadhan, Sp.OT",
        specialty: "Ortopedi",
        schedule: "Senin – Jumat, 09:00–14:00",
      },
    ],
    operational_hours: [{ day: "IGD", hours: "Buka 24 Jam" }],
    is_active: true,
  },

  // ── DKI Jakarta — rumah sakit khusus & rujukan nasional ────────────────
  {
    slug: "rs-jantung-harapan-kita",
    name: "RS Jantung dan Pembuluh Darah Harapan Kita",
    short_name: "RS Jantung Harapan Kita",
    location: "Jakarta Barat",
    province: "DKI Jakarta",
    address:
      "Jl. Letjen S. Parman Kav. 87, Slipi, Palmerah, Jakarta Barat 11420",
    phone: "(021) 5684093",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Jantung",
    description:
      "Pusat Jantung Nasional Harapan Kita adalah rumah sakit rujukan tertinggi untuk penyakit jantung dan pembuluh darah di Indonesia, dengan layanan bedah jantung, kateterisasi, dan elektrofisiologi.",
    image_url: "https://kemenkesrs.s3.ap-southeast-3.amazonaws.com/14129/RSJPD-Harapan-Kita.webp",
    is_open_24h: true,
    closing_time: null,
    beds: 435,
    established: 1985,
    services: [
      "IGD Jantung 24 Jam",
      "Bedah Jantung",
      "Kateterisasi Jantung",
      "Elektrofisiologi",
      "Rehabilitasi Jantung",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICCU",
      "Cath Lab",
      "Kamar Operasi Jantung",
      "CT Scan",
      "MRI Kardiak",
      "Echocardiography",
    ],
    specialists: [
      {
        name: "Dr. Bimo Prasetyo, Sp.JP(K)",
        specialty: "Kardiologi Intervensi",
        schedule: "Senin – Jumat, 08:00–14:00",
        image_id: "1612349317-34f14cbbdef8",
      },
      {
        name: "Dr. Renata Salim, Sp.BTKV",
        specialty: "Bedah Toraks Kardiovaskular",
        schedule: "Selasa & Kamis, 09:00–13:00",
        image_id: "1559839734-2b71ea197ec2",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 15:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rs-kanker-dharmais",
    name: "RS Kanker Dharmais",
    short_name: "RS Dharmais",
    location: "Jakarta Barat",
    province: "DKI Jakarta",
    address: "Jl. Letjen S. Parman Kav. 84-86, Slipi, Jakarta Barat 11420",
    phone: "(021) 5681570",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Kanker",
    description:
      "RS Kanker Dharmais adalah pusat kanker nasional yang menyediakan layanan pencegahan, deteksi dini, pengobatan, dan paliatif kanker secara terpadu.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Dharmais_Hospital.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 424,
    established: 1993,
    services: [
      "IGD 24 Jam",
      "Kemoterapi",
      "Radioterapi",
      "Bedah Onkologi",
      "Perawatan Paliatif",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Radioterapi (LINAC)",
      "PET Scan",
      "MRI",
      "Bank Darah",
      "Apotek 24 Jam",
    ],
    specialists: [
      {
        name: "Dr. Hesti Wulandari, Sp.PD-KHOM",
        specialty: "Hematologi Onkologi Medik",
        schedule: "Senin – Jumat, 09:00–14:00",
        image_id: "1594824476967-bef8d2f54537",
      },
      {
        name: "Dr. Fajar Nugroho, Sp.Onk.Rad",
        specialty: "Onkologi Radiasi",
        schedule: "Senin, Rabu, Jumat, 08:00–13:00",
        image_id: "1582750433449-648ed127bb54",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 15:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rsab-harapan-kita",
    name: "RSAB Harapan Kita",
    short_name: "RSAB Harapan Kita",
    location: "Jakarta Barat",
    province: "DKI Jakarta",
    address: "Jl. Letjen S. Parman Kav. 87, Slipi, Jakarta Barat 11420",
    phone: "(021) 5668284",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "B",
    category: "Rumah Sakit Ibu dan Anak (RSIA)",
    description:
      "Rumah Sakit Anak dan Bunda Harapan Kita adalah rumah sakit rujukan nasional untuk kesehatan ibu dan anak, dengan layanan perinatologi, fetomaternal, dan bedah anak.",
    image_url: "https://kemenkesrs.s3.ap-southeast-3.amazonaws.com/14119/Gedung-RSAB-edit.webp",
    is_open_24h: true,
    closing_time: null,
    beds: 300,
    established: 1979,
    services: [
      "IGD 24 Jam",
      "Perinatologi",
      "Fetomaternal",
      "Bedah Anak",
      "Klinik Tumbuh Kembang",
    ],
    facilities: [
      "IGD 24 Jam",
      "NICU",
      "PICU",
      "Kamar Bersalin",
      "USG 4D",
      "Laboratorium",
      "Ruang Laktasi",
    ],
    specialists: [
      {
        name: "Dr. Sarah Wijaya, Sp.OG(K)",
        specialty: "Fetomaternal",
        schedule: "Senin – Jumat, 08:00–14:00",
        image_id: "1594824476967-bef8d2f54537",
      },
      {
        name: "Dr. Adit Kurniawan, Sp.A(K)",
        specialty: "Neonatologi",
        schedule: "Setiap hari (on-call)",
        image_id: "1612349317-34f14cbbdef8",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 15:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rsup-fatmawati-jakarta",
    name: "RSUP Fatmawati",
    short_name: "RS Fatmawati",
    location: "Jakarta Selatan",
    province: "DKI Jakarta",
    address:
      "Jl. RS Fatmawati Raya No. 4, Cilandak Barat, Jakarta Selatan 12430",
    phone: "(021) 7501524",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP Fatmawati adalah rumah sakit rujukan nasional dengan layanan unggulan ortopedi dan rehabilitasi medik, serta pusat pendidikan kedokteran.",
    image_url: "https://upload.wikimedia.org/wikipedia/id/2/2e/RSUPF_tampak_depan.jpeg",
    is_open_24h: true,
    closing_time: null,
    beds: 850,
    established: 1961,
    services: [
      "IGD 24 Jam",
      "Ortopedi Terpadu",
      "Rehabilitasi Medik",
      "Onkologi",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Kamar Operasi",
      "CT Scan",
      "MRI",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Galih Pranata, Sp.OT(K)",
        specialty: "Ortopedi — Spine",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1582750433449-648ed127bb54",
      },
      {
        name: "Dr. Wulan Sari, Sp.KFR",
        specialty: "Kedokteran Fisik & Rehabilitasi",
        schedule: "Selasa – Kamis, 09:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 15:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Banten ─────────────────────────────────────────────────────────────
  {
    slug: "rsud-kabupaten-tangerang",
    name: "RSUD Kabupaten Tangerang",
    short_name: "RSUD Tangerang",
    location: "Tangerang",
    province: "Banten",
    address: "Jl. A. Yani No. 9, Sukaasih, Tangerang, Kota Tangerang 15111",
    phone: "(021) 5523507",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Kabupaten Tangerang adalah rumah sakit rujukan milik Pemerintah Kabupaten Tangerang dengan layanan spesialis lengkap dan pusat trauma regional.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 460,
    established: 1928,
    services: [
      "IGD 24 Jam",
      "Trauma Center",
      "Penyakit Dalam",
      "Bedah",
      "Kebidanan & Kandungan",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "NICU",
      "Kamar Operasi",
      "Hemodialisis",
      "Laboratorium",
    ],
    specialists: [
      {
        name: "Dr. Hariyanto, Sp.B",
        specialty: "Bedah Umum",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1582750433449-648ed127bb54",
      },
      {
        name: "Dr. Melati Anggraini, Sp.OG",
        specialty: "Kebidanan & Kandungan",
        schedule: "Senin – Sabtu, 09:00–14:00",
        image_id: "1594824476967-bef8d2f54537",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Jawa Barat ─────────────────────────────────────────────────────────
  {
    slug: "pmn-rs-mata-cicendo-bandung",
    name: "PMN RS Mata Cicendo",
    short_name: "RS Mata Cicendo",
    location: "Bandung",
    province: "Jawa Barat",
    address: "Jl. Cicendo No. 4, Babakan Ciamis, Sumur Bandung, Kota Bandung 40117",
    phone: "(022) 4231280",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Mata",
    description:
      "Pusat Mata Nasional RS Mata Cicendo adalah rumah sakit rujukan tertinggi untuk kesehatan mata di Indonesia, dengan layanan katarak, glaukoma, retina, dan bedah refraktif.",
    image_url: "https://kemenkesrs.s3.ap-southeast-3.amazonaws.com/26/cicendo.webp",
    is_open_24h: true,
    closing_time: null,
    beds: 120,
    established: 1909,
    services: [
      "IGD Mata 24 Jam",
      "Bedah Katarak",
      "Layanan Glaukoma",
      "Layanan Retina",
      "Bedah Refraktif (LASIK)",
    ],
    facilities: [
      "IGD Mata 24 Jam",
      "Kamar Operasi Mikro",
      "Laser Fotokoagulasi",
      "OCT",
      "Bank Mata",
      "Apotek",
    ],
    specialists: [
      {
        name: "Dr. Prita Larasati, Sp.M(K)",
        specialty: "Vitreoretina",
        schedule: "Senin – Jumat, 08:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
      {
        name: "Dr. Danang Suryo, Sp.M(K)",
        specialty: "Glaukoma",
        schedule: "Selasa & Kamis, 09:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 15:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rsud-al-ihsan-bandung",
    name: "RSUD Al-Ihsan Provinsi Jawa Barat",
    short_name: "RSUD Al-Ihsan",
    location: "Kabupaten Bandung",
    province: "Jawa Barat",
    address: "Jl. Kiastramanggala, Baleendah, Kabupaten Bandung 40381",
    phone: "(022) 5940872",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Al-Ihsan adalah rumah sakit milik Pemerintah Provinsi Jawa Barat dengan pelayanan spesialis lengkap dan nuansa pelayanan islami.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 430,
    established: 1993,
    services: [
      "IGD 24 Jam",
      "Penyakit Dalam",
      "Bedah",
      "Anak",
      "Jantung",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Kamar Operasi",
      "Hemodialisis",
      "CT Scan",
      "Laboratorium",
    ],
    specialists: [
      {
        name: "Dr. Taufik Hidayat, Sp.PD",
        specialty: "Penyakit Dalam",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Nadia Rahma, Sp.A",
        specialty: "Kesehatan Anak",
        schedule: "Senin – Sabtu, 09:00–14:00",
        image_id: "1612349317-34f14cbbdef8",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rs-hermina-depok",
    name: "RS Hermina Depok",
    short_name: "Hermina Depok",
    location: "Depok",
    province: "Jawa Barat",
    address: "Jl. Siliwangi No. 50, Pancoran Mas, Kota Depok 16436",
    phone: "(021) 77202525",
    type: "Rumah Sakit Swasta",
    hospital_class: "C",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RS Hermina Depok adalah rumah sakit swasta dengan layanan unggulan ibu dan anak, melayani BPJS Kesehatan dan asuransi swasta.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 205,
    established: 2001,
    services: [
      "IGD 24 Jam",
      "Ibu & Anak",
      "Penyakit Dalam",
      "Bedah Umum",
      "Poli Gigi",
    ],
    facilities: [
      "IGD 24 Jam",
      "NICU",
      "Kamar Bersalin",
      "Kamar Operasi",
      "Laboratorium",
      "Apotek",
    ],
    specialists: [
      {
        name: "Dr. Indah Permata, Sp.OG",
        specialty: "Kebidanan & Kandungan",
        schedule: "Senin – Sabtu, 08:00–20:00",
        image_id: "1594824476967-bef8d2f54537",
      },
      {
        name: "Dr. Reza Alfian, Sp.A",
        specialty: "Kesehatan Anak",
        schedule: "Setiap hari, 08:00–21:00",
        image_id: "1612349317-34f14cbbdef8",
      },
    ],
    operational_hours: [{ day: "IGD", hours: "Buka 24 Jam" }],
    is_active: true,
  },

  // ── Jawa Tengah ────────────────────────────────────────────────────────
  {
    slug: "rsud-dr-moewardi-surakarta",
    name: "RSUD Dr. Moewardi",
    short_name: "RS Dr. Moewardi",
    location: "Surakarta",
    province: "Jawa Tengah",
    address: "Jl. Kolonel Sutarto No. 132, Jebres, Kota Surakarta 57126",
    phone: "(0271) 634634",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Dr. Moewardi adalah rumah sakit milik Pemerintah Provinsi Jawa Tengah dan pusat rujukan untuk wilayah Solo Raya, terintegrasi dengan FK UNS.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 800,
    established: 1912,
    services: [
      "IGD 24 Jam",
      "Jantung Terpadu",
      "Onkologi",
      "Bedah Saraf",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "MRI",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Prasetya Adi, Sp.JP(K)",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1612349317-34f14cbbdef8",
      },
      {
        name: "Dr. Larasati Dewi, Sp.S",
        specialty: "Neurologi",
        schedule: "Selasa & Kamis, 09:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rs-ortopedi-prof-soeharso-surakarta",
    name: "RS Ortopedi Prof. Dr. R. Soeharso",
    short_name: "RSO Prof. Soeharso",
    location: "Surakarta",
    province: "Jawa Tengah",
    address: "Jl. Ahmad Yani, Pabelan, Kartasura, Kabupaten Sukoharjo 57162",
    phone: "(0271) 714458",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Ortopedi",
    description:
      "RS Ortopedi Prof. Dr. R. Soeharso adalah rumah sakit rujukan nasional untuk bidang ortopedi, traumatologi, dan rehabilitasi medik muskuloskeletal.",
    image_url: "https://kemenkesrs.s3.ap-southeast-3.amazonaws.com/14116/yandu-baru2.webp",
    is_open_24h: true,
    closing_time: null,
    beds: 220,
    established: 1946,
    services: [
      "IGD 24 Jam",
      "Bedah Ortopedi",
      "Bedah Tulang Belakang",
      "Rehabilitasi Medik",
      "Bengkel Ortotik Prostetik",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Kamar Operasi",
      "C-Arm",
      "Fisioterapi",
      "Bengkel Prostetik",
    ],
    specialists: [
      {
        name: "Dr. Wisnu Broto, Sp.OT(K)",
        specialty: "Ortopedi — Rekonstruksi",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1582750433449-648ed127bb54",
      },
      {
        name: "Dr. Ayu Kartika, Sp.KFR",
        specialty: "Kedokteran Fisik & Rehabilitasi",
        schedule: "Selasa & Kamis, 09:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rsud-margono-soekarjo-purwokerto",
    name: "RSUD Prof. Dr. Margono Soekarjo",
    short_name: "RSMS Purwokerto",
    location: "Purwokerto",
    province: "Jawa Tengah",
    address:
      "Jl. Dr. Gumbreg No. 1, Berkoh, Purwokerto Selatan, Kabupaten Banyumas 53146",
    phone: "(0281) 632708",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Prof. Dr. Margono Soekarjo adalah rumah sakit rujukan milik Pemerintah Provinsi Jawa Tengah untuk wilayah Banyumas Raya.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 700,
    established: 1946,
    services: [
      "IGD 24 Jam",
      "Jantung",
      "Onkologi",
      "Stroke Center",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "Hemodialisis",
      "Laboratorium",
    ],
    specialists: [
      {
        name: "Dr. Bayu Saputra, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Sekar Ayu, Sp.S",
        specialty: "Neurologi",
        schedule: "Selasa & Kamis, 09:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Jawa Timur ─────────────────────────────────────────────────────────
  {
    slug: "rsud-dr-saiful-anwar-malang",
    name: "RSUD Dr. Saiful Anwar",
    short_name: "RSSA Malang",
    location: "Malang",
    province: "Jawa Timur",
    address: "Jl. Jaksa Agung Suprapto No. 2, Klojen, Kota Malang 65112",
    phone: "(0341) 362101",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Dr. Saiful Anwar adalah rumah sakit rujukan tersier milik Pemerintah Provinsi Jawa Timur untuk wilayah Malang Raya, terintegrasi dengan FK Universitas Brawijaya.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 950,
    established: 1979,
    services: [
      "IGD 24 Jam",
      "Jantung Terpadu",
      "Onkologi",
      "Bedah Saraf",
      "Luka Bakar",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "MRI",
      "Unit Luka Bakar",
    ],
    specialists: [
      {
        name: "Dr. Hendra Wijaya, Sp.BS",
        specialty: "Bedah Saraf",
        schedule: "Senin, Rabu, Jumat, 08:00–12:00",
        image_id: "1582750433449-648ed127bb54",
      },
      {
        name: "Dr. Ratna Kusuma, Sp.PD-KHOM",
        specialty: "Hematologi Onkologi Medik",
        schedule: "Selasa & Kamis, 09:00–14:00",
        image_id: "1594824476967-bef8d2f54537",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
  {
    slug: "rsj-menur-surabaya",
    name: "RS Jiwa Menur",
    short_name: "RSJ Menur",
    location: "Surabaya",
    province: "Jawa Timur",
    address: "Jl. Menur No. 120, Mojo, Gubeng, Kota Surabaya 60282",
    phone: "(031) 5021635",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Jiwa (RSJ)",
    description:
      "RS Jiwa Menur adalah rumah sakit khusus jiwa milik Pemerintah Provinsi Jawa Timur dengan layanan psikiatri, psikologi klinis, dan rehabilitasi napza.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 300,
    established: 1923,
    services: [
      "IGD Psikiatri 24 Jam",
      "Rawat Inap Jiwa",
      "Klinik Psikologi",
      "Rehabilitasi Napza",
      "Klinik Tumbuh Kembang",
    ],
    facilities: [
      "IGD 24 Jam",
      "Ruang Rawat Intensif Psikiatri",
      "Ruang Rehabilitasi",
      "Klinik Elektromedik (ECT)",
      "Laboratorium",
      "Apotek",
    ],
    specialists: [
      {
        name: "Dr. Anton Prabowo, Sp.KJ",
        specialty: "Psikiatri",
        schedule: "Senin – Jumat, 08:00–14:00",
        image_id: "1582750433449-648ed127bb54",
      },
      {
        name: "Dr. Maharani Putri, Sp.KJ",
        specialty: "Psikiatri Anak & Remaja",
        schedule: "Selasa & Kamis, 09:00–13:00",
        image_id: "1594824476967-bef8d2f54537",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "07:30 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── DI Yogyakarta ──────────────────────────────────────────────────────
  {
    slug: "rs-bethesda-yogyakarta",
    name: "RS Bethesda Yogyakarta",
    short_name: "RS Bethesda",
    location: "Kota Yogyakarta",
    province: "DI Yogyakarta",
    address: "Jl. Jenderal Sudirman No. 70, Kotabaru, Gondokusuman, Kota Yogyakarta 55224",
    phone: "(0274) 586688",
    type: "Rumah Sakit Swasta",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RS Bethesda adalah rumah sakit swasta tertua di Yogyakarta dengan layanan stroke terpadu, jantung, dan trauma.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/7/74/RS_Bethesda_2024.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 400,
    established: 1899,
    services: [
      "IGD 24 Jam",
      "Stroke Center",
      "Jantung",
      "Bedah",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Stroke Unit",
      "CT Scan",
      "MRI",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Christian Nugroho, Sp.S",
        specialty: "Neurologi",
        schedule: "Senin – Jumat, 08:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
      {
        name: "Dr. Dian Pertiwi, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Selasa & Kamis, 09:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
    ],
    operational_hours: [{ day: "IGD", hours: "Buka 24 Jam" }],
    is_active: true,
  },

  // ── Bali ───────────────────────────────────────────────────────────────
  {
    slug: "rsud-bali-mandara-denpasar",
    name: "RSUD Bali Mandara",
    short_name: "RSUD Bali Mandara",
    location: "Denpasar",
    province: "Bali",
    address: "Jl. Bypass Ngurah Rai No. 548, Sanur Kauh, Denpasar Selatan, Kota Denpasar 80228",
    phone: "(0361) 4490100",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Bali Mandara adalah rumah sakit milik Pemerintah Provinsi Bali dengan layanan unggulan jantung, ginjal, dan kanker.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 300,
    established: 2017,
    services: [
      "IGD 24 Jam",
      "Jantung",
      "Hemodialisis",
      "Onkologi",
      "Penyakit Dalam",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "Hemodialisis",
      "Laboratorium",
    ],
    specialists: [
      {
        name: "Dr. Putu Ariawan, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1612349317-34f14cbbdef8",
      },
      {
        name: "Dr. Kadek Sari, Sp.PD-KGH",
        specialty: "Nefrologi",
        schedule: "Selasa & Kamis, 09:00–14:00",
        image_id: "1594824476967-bef8d2f54537",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Aceh ───────────────────────────────────────────────────────────────
  {
    slug: "rsud-dr-zainoel-abidin-banda-aceh",
    name: "RSUD Dr. Zainoel Abidin",
    short_name: "RSUDZA",
    location: "Banda Aceh",
    province: "Aceh",
    address: "Jl. Tgk. Daud Beureueh No. 108, Bandar Baru, Kuta Alam, Kota Banda Aceh 24415",
    phone: "(0651) 34565",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Dr. Zainoel Abidin adalah rumah sakit rujukan tersier milik Pemerintah Aceh, terintegrasi dengan FK Universitas Syiah Kuala.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 700,
    established: 1979,
    services: [
      "IGD 24 Jam",
      "Jantung Terpadu",
      "Onkologi",
      "Bedah Saraf",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "MRI",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Teuku Farhan, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Cut Nyak Dhien, Sp.OG",
        specialty: "Kebidanan & Kandungan",
        schedule: "Selasa & Kamis, 09:00–14:00",
        image_id: "1594824476967-bef8d2f54537",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Sumatera Barat ─────────────────────────────────────────────────────
  {
    slug: "rsup-dr-m-djamil-padang",
    name: "RSUP Dr. M. Djamil",
    short_name: "RS M. Djamil",
    location: "Padang",
    province: "Sumatera Barat",
    address: "Jl. Perintis Kemerdekaan No. 94, Jati, Padang Timur, Kota Padang 25129",
    phone: "(0751) 32373",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP Dr. M. Djamil adalah rumah sakit rujukan tertinggi untuk wilayah Sumatera bagian tengah, terintegrasi dengan FK Universitas Andalas.",
    image_url:
      "https://kemenkesrs.s3.ap-southeast-3.amazonaws.com/14131/rsdjamil2.webp",
    is_open_24h: true,
    closing_time: null,
    beds: 800,
    established: 1953,
    services: [
      "IGD 24 Jam",
      "Jantung Terpadu",
      "Onkologi",
      "Bedah Saraf",
      "Trauma Center",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "MRI",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Fadli Rahman, Sp.BS",
        specialty: "Bedah Saraf",
        schedule: "Senin, Rabu, Jumat, 08:00–12:00",
        image_id: "1582750433449-648ed127bb54",
      },
      {
        name: "Dr. Sari Bulan, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Selasa & Kamis, 09:00–14:00",
        image_id: "1612349317-34f14cbbdef8",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Riau ───────────────────────────────────────────────────────────────
  {
    slug: "rsud-arifin-achmad-pekanbaru",
    name: "RSUD Arifin Achmad",
    short_name: "RSUD Arifin Achmad",
    location: "Pekanbaru",
    province: "Riau",
    address: "Jl. Diponegoro No. 2, Sumahilang, Pekanbaru Kota, Kota Pekanbaru 28156",
    phone: "(0761) 21618",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Arifin Achmad adalah rumah sakit rujukan milik Pemerintah Provinsi Riau dengan layanan spesialis dan sebagian subspesialis.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 500,
    established: 1950,
    services: [
      "IGD 24 Jam",
      "Jantung",
      "Onkologi",
      "Penyakit Dalam",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "Hemodialisis",
      "Laboratorium",
    ],
    specialists: [
      {
        name: "Dr. Rahmat Hidayat, Sp.PD",
        specialty: "Penyakit Dalam",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Nurhaliza, Sp.A",
        specialty: "Kesehatan Anak",
        schedule: "Senin – Sabtu, 09:00–14:00",
        image_id: "1612349317-34f14cbbdef8",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Jambi ──────────────────────────────────────────────────────────────
  {
    slug: "rsud-raden-mattaher-jambi",
    name: "RSUD Raden Mattaher",
    short_name: "RSUD Raden Mattaher",
    location: "Jambi",
    province: "Jambi",
    address: "Jl. Letjen Suprapto No. 31, Telanaipura, Kota Jambi 36122",
    phone: "(0741) 61692",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Raden Mattaher adalah rumah sakit rujukan milik Pemerintah Provinsi Jambi, terintegrasi dengan FK Universitas Jambi.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 400,
    established: 1972,
    services: [
      "IGD 24 Jam",
      "Penyakit Dalam",
      "Bedah",
      "Kebidanan & Kandungan",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Kamar Operasi",
      "CT Scan",
      "Hemodialisis",
      "Laboratorium",
    ],
    specialists: [
      {
        name: "Dr. Bambang Irawan, Sp.B",
        specialty: "Bedah Umum",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1582750433449-648ed127bb54",
      },
      {
        name: "Dr. Siti Aisyah, Sp.OG",
        specialty: "Kebidanan & Kandungan",
        schedule: "Senin – Sabtu, 09:00–14:00",
        image_id: "1594824476967-bef8d2f54537",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Lampung ────────────────────────────────────────────────────────────
  {
    slug: "rsud-abdul-moeloek-bandar-lampung",
    name: "RSUD Dr. H. Abdul Moeloek",
    short_name: "RSUDAM",
    location: "Bandar Lampung",
    province: "Lampung",
    address: "Jl. Dr. Rivai No. 6, Penengahan, Tanjung Karang Pusat, Kota Bandar Lampung 35112",
    phone: "(0721) 703312",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Dr. H. Abdul Moeloek adalah rumah sakit rujukan tertinggi milik Pemerintah Provinsi Lampung.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 700,
    established: 1914,
    services: [
      "IGD 24 Jam",
      "Jantung Terpadu",
      "Onkologi",
      "Stroke Center",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "MRI",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Agus Salim, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Ratih Purnama, Sp.S",
        specialty: "Neurologi",
        schedule: "Selasa & Kamis, 09:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Kalimantan Barat ───────────────────────────────────────────────────
  {
    slug: "rsud-dr-soedarso-pontianak",
    name: "RSUD Dr. Soedarso",
    short_name: "RSUD Soedarso",
    location: "Pontianak",
    province: "Kalimantan Barat",
    address: "Jl. Dr. Soedarso, Bangka Belitung Laut, Pontianak Tenggara, Kota Pontianak 78124",
    phone: "(0561) 737701",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Dr. Soedarso adalah rumah sakit rujukan milik Pemerintah Provinsi Kalimantan Barat.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Instalasi_Gawat_Darurat_RSUD_dr_Soedarso_Pontianak_%282026%29_01.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 400,
    established: 1970,
    services: [
      "IGD 24 Jam",
      "Penyakit Dalam",
      "Bedah",
      "Anak",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Kamar Operasi",
      "CT Scan",
      "Hemodialisis",
      "Laboratorium",
    ],
    specialists: [
      {
        name: "Dr. Herman Susanto, Sp.PD",
        specialty: "Penyakit Dalam",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Fransiska Dewi, Sp.A",
        specialty: "Kesehatan Anak",
        schedule: "Senin – Sabtu, 09:00–14:00",
        image_id: "1612349317-34f14cbbdef8",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Kalimantan Selatan ─────────────────────────────────────────────────
  {
    slug: "rsud-ulin-banjarmasin",
    name: "RSUD Ulin",
    short_name: "RSUD Ulin",
    location: "Banjarmasin",
    province: "Kalimantan Selatan",
    address: "Jl. A. Yani No. 43, Sungai Baru, Banjarmasin Tengah, Kota Banjarmasin 70233",
    phone: "(0511) 3252180",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Ulin adalah rumah sakit rujukan tertinggi milik Pemerintah Provinsi Kalimantan Selatan, terintegrasi dengan FK Universitas Lambung Mangkurat.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Rumah_Sakit_Umum_Daerah_Ulin_Banjarmasin_2025.jpg",
    is_open_24h: true,
    closing_time: null,
    beds: 700,
    established: 1943,
    services: [
      "IGD 24 Jam",
      "Jantung Terpadu",
      "Onkologi",
      "Bedah Saraf",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "MRI",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Rizky Amelia, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1612349317-34f14cbbdef8",
      },
      {
        name: "Dr. Gusti Ngurah, Sp.BS",
        specialty: "Bedah Saraf",
        schedule: "Senin, Rabu, Jumat, 08:00–12:00",
        image_id: "1582750433449-648ed127bb54",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Sulawesi Utara ─────────────────────────────────────────────────────
  {
    slug: "rsup-prof-kandou-manado",
    name: "RSUP Prof. Dr. R. D. Kandou",
    short_name: "RS Kandou",
    location: "Manado",
    province: "Sulawesi Utara",
    address: "Jl. Raya Tanawangko No. 56, Bahu, Malalayang, Kota Manado 95162",
    phone: "(0431) 838203",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "A",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUP Prof. Dr. R. D. Kandou adalah rumah sakit rujukan tertinggi untuk wilayah Sulawesi bagian utara, terintegrasi dengan FK Universitas Sam Ratulangi.",
    image_url: "https://kemenkesrs.s3.ap-southeast-3.amazonaws.com/14140/75_Untitled-design.webp",
    is_open_24h: true,
    closing_time: null,
    beds: 800,
    established: 1954,
    services: [
      "IGD 24 Jam",
      "Jantung Terpadu",
      "Onkologi",
      "Stroke Center",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Cath Lab",
      "CT Scan",
      "MRI",
      "Hemodialisis",
    ],
    specialists: [
      {
        name: "Dr. Ventje Kawet, Sp.JP",
        specialty: "Kardiologi",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Grace Tumbelaka, Sp.S",
        specialty: "Neurologi",
        schedule: "Selasa & Kamis, 09:00–14:00",
        image_id: "1559839734-2b71ea197ec2",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },

  // ── Nusa Tenggara Timur ────────────────────────────────────────────────
  {
    slug: "rsud-prof-johannes-kupang",
    name: "RSUD Prof. Dr. W. Z. Johannes",
    short_name: "RSUD W. Z. Johannes",
    location: "Kupang",
    province: "Nusa Tenggara Timur",
    address: "Jl. Dr. Moch. Hatta No. 19, Oetete, Oebobo, Kota Kupang 85111",
    phone: "(0380) 832892",
    type: "Rumah Sakit Pemerintah",
    hospital_class: "B",
    category: "Rumah Sakit Umum (RSU)",
    description:
      "RSUD Prof. Dr. W. Z. Johannes adalah rumah sakit rujukan tertinggi milik Pemerintah Provinsi Nusa Tenggara Timur.",
    image_url: "",
    is_open_24h: true,
    closing_time: null,
    beds: 350,
    established: 1938,
    services: [
      "IGD 24 Jam",
      "Penyakit Dalam",
      "Bedah",
      "Kebidanan & Kandungan",
      "Hemodialisis",
    ],
    facilities: [
      "IGD 24 Jam",
      "ICU",
      "Kamar Operasi",
      "CT Scan",
      "Hemodialisis",
      "Laboratorium",
    ],
    specialists: [
      {
        name: "Dr. Yohanes Riwu, Sp.PD",
        specialty: "Penyakit Dalam",
        schedule: "Senin – Jumat, 08:00–13:00",
        image_id: "1607990281399-e5fb2df2cbb4",
      },
      {
        name: "Dr. Maria Bunga, Sp.OG",
        specialty: "Kebidanan & Kandungan",
        schedule: "Senin – Sabtu, 09:00–14:00",
        image_id: "1594824476967-bef8d2f54537",
      },
    ],
    operational_hours: [
      { day: "IGD", hours: "Buka 24 Jam" },
      { day: "Poliklinik", hours: "08:00 – 14:00 (Senin – Jumat)" },
    ],
    is_active: true,
  },
]
